
package br.com.gabriel.estoque.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-07-24T16:12:39.445-03:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "AutorizacaoFault", targetNamespace = "http://ws.estoque.gabriel.com.br/")
public class AutorizacaoFault extends Exception {

    private InfoFault faultInfo;

    public AutorizacaoFault() {
        super();
    }

    public AutorizacaoFault(String message) {
        super(message);
    }

    public AutorizacaoFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AutorizacaoFault(String message, InfoFault autorizacaoFault) {
        super(message);
        this.faultInfo = autorizacaoFault;
    }

    public AutorizacaoFault(String message, InfoFault autorizacaoFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = autorizacaoFault;
    }

    public InfoFault getFaultInfo() {
        return this.faultInfo;
    }
}
