package br.com.gabriel.estoque.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-07-24T16:12:39.474-03:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://ws.estoque.gabriel.com.br/", name = "EstoqueWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EstoqueWS {

    @WebMethod(operationName = "TodosOsItens")
    @Action(input = "http://ws.estoque.gabriel.com.br/EstoqueWS/TodosOsItensRequest", output = "http://ws.estoque.gabriel.com.br/EstoqueWS/TodosOsItensResponse")
    @RequestWrapper(localName = "TodosOsItens", targetNamespace = "http://ws.estoque.gabriel.com.br/", className = "br.com.gabriel.estoque.ws.generated.TodosOsItens")
    @ResponseWrapper(localName = "itens", targetNamespace = "http://ws.estoque.gabriel.com.br/", className = "br.com.gabriel.estoque.ws.generated.Itens")
    @WebResult(name = "itens", targetNamespace = "")
    public ListaItens todosOsItens(

        @WebParam(name = "filtros", targetNamespace = "")
        Filtros filtros
    );

    @WebMethod(operationName = "CadastrarItem")
    @Action(input = "http://ws.estoque.gabriel.com.br/EstoqueWS/CadastrarItemRequest", output = "http://ws.estoque.gabriel.com.br/EstoqueWS/CadastrarItemResponse", fault = {@FaultAction(className = AutorizacaoFault.class, value = "http://ws.estoque.gabriel.com.br/EstoqueWS/CadastrarItem/Fault/AutorizacaoException")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CadastrarItemResponse", targetNamespace = "http://ws.estoque.gabriel.com.br/", partName = "result")
    public CadastrarItemResponse cadastrarItem(

        @WebParam(partName = "parameters", name = "CadastrarItem", targetNamespace = "http://ws.estoque.gabriel.com.br/")
        CadastrarItem parameters,
        @WebParam(partName = "tokenUsuario", name = "tokenUsuario", targetNamespace = "http://ws.estoque.gabriel.com.br/", header = true)
        TokenUsuario tokenUsuario
    ) throws AutorizacaoFault;
}
